name: Deploy Next.js to Azure App Service

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: 'azure-nextjs-sample-from-guide-gde7ckachxb4cdaq'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund
        timeout-minutes: 5

      - name: Build application
        run: npm run build
        timeout-minutes: 5
        # env:
        #   NEXT_PUBLIC_API_URL: https://app-002-gen10-step3-1-py-oshima36.azurewebsites.net

      - name: Copy standalone files
        run: |
          cp -r .next/standalone ./deploy
          cp -r .next/static ./deploy/.next/static
          cp -r public ./deploy/public

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: './deploy'
          slot-name: ''

      # - name: Deploy to Azure App Service
      #   uses: azure/webapps-deploy@v3
      #   timeout-minutes: 10
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME  }}
      #     creds: ${{ secrets.AZURE_CREDENTIALS }} # <-- publish-profileの代わりにこれを指定
      #     package: './deploy'
      #     slot-name: '' # <-- この一行を追加します(Freeプランだから追加してる)
          # app-name: ${{ env.AZURE_WEBAPP_NAME }}
          # publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # package: './deploy'
          # slot-name: '' # <-- この一行を追加します(Freeプランだから追加してる)